version: 0.2

run-as: root

env:
  git-credential-helper: yes
  shell: bash
  secrets-manager:
    AWS_ACCESS_KEY: ${IW_AWS_ACCESS_KEY_ARN}
    AWS_SECRET_KEY: ${IW_AWS_ACCESS_SECRET_ARN}

batch:
  fast-fail: true

phases:
  install:
    run-as: root
    on-failure: ABORT
    commands:
      - sudo yum -y install git maven awscli
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY 
      - aws configure set aws_secret_access_key $AWS_SECRET_KEY
      - aws s3 cp $IW_JDK_PACKAGE_S3_PATH .
      - aws s3 cp $IW_MAVEN_SETTINGS_S3_PATH .
      - rpm -ivh --nodigest --nofiledigest $IW_JDK_PACKAGE_FILE_NAME
      - rm -f $IW_JDK_PACKAGE_FILE_NAME
      - mv settings.xml $HOME/.m2/settings.xml
  pre_build:
    run-as: root
    on-failure: ABORT
    commands:
      - export readonly CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $IW_CODE_ART_DOMAIN --domain-owner $IW_CODE_ART_DOMAIN_OWNER --query authorizationToken --output text --region $IW_CODE_ART_DOMAIN_REGION)
      - cd $CODEBUILD_SRC_DIR_PLATFORM
      - git checkout BRANCH_PLATFORM_5
      - git pull
      - git submodule update --init --recursive --remote
      - git submodule foreach git checkout BRANCH_PLATFORM_5
      - git submodule foreach git pull
      - cd $CODEBUILD_SRC_DIR_ADDON
      - git checkout BRANCH_PLATFORM_5
      - git pull
      - git submodule update --init --recursive --remote
      - git submodule foreach git checkout BRANCH_PLATFORM_5
      - git submodule foreach git pull
      - cd $CODEBUILD_SRC_DIR_EGOV
      - git checkout BRANCH_PLATFORM_5
      - git pull
      - git submodule update --init --recursive --remote
      - git submodule foreach git checkout BRANCH_PLATFORM_5
      - git submodule foreach git pull
      - cd $CODEBUILD_SRC_DIR_PRIVATE
      - git checkout BRANCH_PLATFORM_5
      - git pull
      - git submodule update --init --recursive --remote
      - git submodule foreach git checkout BRANCH_PLATFORM_5
      - git submodule foreach git pull
      - cd $CODEBUILD_SRC_DIR_PRIVATE/com.idega.camunda
      - git checkout field-attribute
      - cd $CODEBUILD_SRC_DIR_WEBAPP
      - git checkout BRANCH_PLATFORM_5
      - git pull
  build:
    run-as: root
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR_PLATFORM
      - mvn clean install -DskipTests
      - cd $CODEBUILD_SRC_DIR_ADDON
      - mvn clean install -DskipTests
      - cd $CODEBUILD_SRC_DIR_EGOV
      - mvn clean install -DskipTests
      - cd $CODEBUILD_SRC_DIR_PRIVATE
      - mvn clean install -DskipTests
      - cd $CODEBUILD_SRC_DIR_WEBAPP
      - mvn clean install -DskipTests
      - cd $CODEBUILD_SRC_DIR
      - mvn clean package install -DskipTests
artifacts:
  files:
    - '**/*'
  base-directory: 'target'

